### ISSUE TITLE
Transaction commit should resolve with an array of successful objectids

### ISSUE THREAD

**Issue by jwasilgeo** [thollingshead/arcgis-server-store#25]
Given the following example:

``` javascript
// Batch updates
var trans = store.transaction();
store.add({NAME: 'New', CATEGORY: 'Sample Transaction'});
store.put({OBJECTID: 2, NAME: 'Edited', CATEGORY: 'Transaction'});
trans.commit();
```

The `commit` should resolve to include information about the successful edit objectids, just as a single, non-batch edit provides the successful objectid.  But right now the `response` in the example below doesn't have any usable info.
`trans.commit().then((response) => console.log(response));`

In the case of mixed batch operations, such as an `add`, `put`, and a `remove`, I'm not sure how this response should be structured. Perhaps the returned objectids should be an array in the same order that batch edit items were added onto the transaction?

**Comment by thollingshead** [comment]
This is not documented in the API, which has sparse information on transactions. However, this seems like a useful feature.

Rather than a single array of mixed ids, I think it would be better for the response to separate the ids by operation.

```
{
    put: [2],
    add: [3]
    remove: []
}
```

Note that this is potentially confusing in the case where the user calls a `put` with a feature that does not exist.

```
var trans = store.transaction();
store.put({NAME: 'No id, so I am considered new'});
trans.commit().then((response) => console.log(response));

// {put: [], add: [4], remove: []}
```
